---
- name: Playbook to execute cronjob output script to find EP2 entry and to fetch the output
  become: true
  become_method: sudo
  hosts: servers

  tasks:

    - name: Execute the shell script to find EP2 entry in cronjob
      script: /root/ansible/files/cronjoboutput.sh
      register: output

    - debug:
        msg: "{{ output.stdout_lines }}"
