---
- name: Playbook to execute EP2 in background 
  become: true
  become_method: sudo
  hosts: servers
  remote_user: pandiasadmin

  tasks:

    - name: Copy EP2 to remote servers with owner and permissions
      copy:
        src: /home/kpandian/ansible/files/EP2v4_5.zip
        dest: /opt/IBM/
        owner: root
        group: root
        mode: '0644'

    - name: Install unzip package to extract EP2
      yum:
        name: unzip
        state: present

    - name: Extract EP2 into /opt/IBM
      unarchive:
        src: /opt/IBM/EP2v4_5.zip
        dest: /opt/IBM/
        remote_src: yes

    - name: Changing file permission to root
      file:
        path: /opt/IBM/EP2v4.5
        owner: root
        group: root 
        mode: '754'
        recurse: yes

    - name: Execute EP2 in background
      shell: cd /opt/IBM/EP2v4.5/app/EP2Source/EP2_CORE_BASH/ && nohup sh EP2_Driver.sh -P &
      ignore_errors: True

