---
- name: Playbook to copy, extract, execute EP2 script
  become: true
  become_method: sudo
  hosts: servers
  remote_user: pandiasadmin
  tasks:
    - name: Copy EP2script zip file to /var/tmp location with owner and permissions
      copy:
        src: /home/vengatr1/ansible/files/EP2441.20180813-020620-597.gold.tar.gz
        dest: /tmp
        owner: root
        group: root
        mode: '0644'
    - name:  Creating the directory structure for EP2.
      shell: cd /home/vengatr1  && mkdir EP2v4.4.1
    - name:  Untar the EP2 zip file
      shell: cd /home/vengatr1/EP2v4.4.1 && tar -xzvf /tmp/EP2441.20180813-020620-597.gold.tar.gz
    - name:  Execute the EP2 driver Script
      shell: nohup /bin/sh /home/vengatr1/EP2v4.4.1/app/EP2Source/EP2_CORE_BASH/EP2_Driver.sh -A -C 0 > /var/tmp/ep2_autocorrect.out &


