---
- name: Playbook to execute EP2 in background 
  become: true
  become_method: sudo
  hosts: servers
  remote_user: pandiasadmin

  tasks:

    - name: Execute EP2 in background
      shell: PATH=/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin && cd /opt/IBM/EP2v4.5/app/EP2Source/EP2_CORE_BASH/ && nohup sh EP2_Driver.sh -P </dev/null >/var/tmp/ep2scan.log 2>&1 &
      ignore_errors: True

