---
- name: To copy files from source to Remote servers
  hosts: servers
  become: yes
  become_method: sudo
  gather_facts: false
  remote_user: pandiasadmin
  tasks:
  - name: Copy files from laptop to remote server
    copy:
      src: "{{ item }}"
      dest: /root
      owner: root
      group: root
      mode: '0740'
    with_items:
      - "/home/kpandian/ansible/files/java-1.8.0-openjdk-1.8.0.181-3.b13.el6_10.x86_64.rpm"
