---
- name: Playbook to execute mef3 script and to fetch the output file 
  become: true
  become_method: sudo
  hosts: servers
  remote_user: kpandian
  tasks:
    - name: Copy mef3 script with owner and permissions
      copy:
        src: /home/kpandian/ansible/files/iam_extract_ibm.sh
        dest: /tmp
        owner: root
        group: root
        mode: '0755'
    - name: Execute mef3 script
      shell: cd /tmp && sh iam_extract_ibm.sh
      ignore_errors: True
    - name: Find the mef3 files under /tmp and register the output
      find:
        paths: /tmp
        patterns: '*.mef3'
        age: "-1h"
      register: findfiles
    - name: Fetch mef3 files from remote server
      fetch:
        src: "{{ item }}"
        dest: /home/kpandian/ansible/mef3output/
        flat: yes
      with_items:
        - "{{ findfiles.files | map(attribute='path') | list }}"



