---
- name: Playbook to change password for user
  hosts: servers
  remote_user: root
  become: yes
  become_method: sudo
  gather_facts: false
  tasks:
  - name: Changing password for user
    user:
      name: "{{ item.user }}"
      update_password: always
      password: "{{ item.password }}"
    with_items:
    - user: "user1" 
      password: '$6$P1ICIrGtX02WFA33$.3PDYB50MVx5B9qeBCeYUc.CJAtu8bvIr26SypG3GxEgeR0RK5.j9a1buASp9orsfwXUFh7/OYlYE2c3iVkuA1'
