---
- name: Playbook to create new user cmfsme with passwords and provide sudo access
  hosts: servers
  remote_user: root
  become: yes
  become_method: sudo
  gather_facts: false
  tasks:
  - name: Creating user cmfsme
    user:
      name: "{{ item.user }}"
      password: "{{ item.password }}"
      update_password: always
    with_items:
    - user: "vengatr1" 
    - password: ''
