---
- name: To change password for user and unlock the account
  hosts: servers
  gather_facts: true
  become: yes
  become_method: sudo

  tasks:

  - name: To change password for user and unlock the account
    user:
      name: "{{ item.user1 }}"
      update_password: always
      password: "{{ item.pass }}"
    with_items:
      - user: soma
        pass: 
      - user: sathish
        pass: 
      - user: deepak
        pass: 

  - name: To unlock account
    user:
      name: test123
      password_lock: no

  - name: To change password for user and unlock the account
    user:
      name: "{{ user2 }}"
      update_password: always
      password: "{{ pass2 }}"

  - name: To unlock account
    user:
      name: test123
      password_lock: no

