---
- name: Playbook to remove logrhythm (scsm) & install azure sentinel (log analytics) agent on Linux servers
  hosts: kaadmin
  gather_facts: true
  become: yes
  become_method: sudo

  tasks:

    - name: Remove logrhythm (scsm) package
      yum:
        name: scsm
        state: absent

    - name: Install sentinel (log analytics) agent
      shell: PATH=/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin && wget https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh && sh onboard_agent.sh -w bffa69a3-7691-4475-b542-eabecc36ff24 -s oSijUiOMbanOyQEWxRsWiZDjp4Kbj6eQ/K3iKVptIqtEWlzpY500VnE6XSsXskMe1gr50ohekTUInVjOmgRJBg==
      ignore_errors: True

