---
- name: To modify PrintMotd value to Yes in SSH config file /etc/ssh/sshd_config
  hosts: servers
  gather_facts: false
  remote_user: dodlasadmin
  become: yes
  become_method: sudo
  tasks:
  - name: To replace PrintMotd value from no to yes
    replace:
      path: /etc/ssh/sshd_config
      regexp: '^PrintMotd no'
      replace: 'PrintMotd yes'
      backup: yes
    notify: reload ssh service
  handlers:
  - name: reload ssh service
    service:
      name: sshd
      state: reloaded 
