---
- name: To remove cbc & arcfour algorithms in SSH
  hosts: servers
  gather_facts: false
  tasks:
  - name: To find the Ciphers line
    shell: 'grep ^Cipher /etc/ssh/sshd_config'
    ignore_errors: true
    register: grep_ciphers
  - name: To replace existing Ciphers if exist  
    replace:
      path: /etc/ssh/sshd_config
      regexp: '(^Ciphers\s)(.*)$'
      replace: '\1aes128-ctr,aes192-ctr,aes256-ctr'
      backup: yes
    when: grep_ciphers.stdout != ""
    notify: restart ssh service
  - name: To add Ciphers line to exclude arcfour & cbc
    lineinfile:
      path: /etc/ssh/sshd_config
      insertafter: '#RekeyLimit'
      line: '{{ item }}'
      backup: yes
    when: grep_ciphers.stdout == ""
    with_items:
    - 'Ciphers aes128-ctr,aes192-ctr,aes256-ctr'
    - '# Restrict Cipher to exclude arcfour & cbc'
    notify: restart ssh service
  handlers:
  - name: restart ssh service
    service:
      name: sshd
      state: restarted 
