---
- name: Playbook to provide sudo access for docmgr
  hosts: servers
  gather_facts: false
  remote_user: pandiasadmin
  become: yes
  become_method: sudo
  tasks:
  - name: To add lines in /etc/sudoers before line Lockdown
    lineinfile:
      path: /etc/sudoers
      insertbefore: "#  Lockdown"
      line: "{{ item }}"
      state: present
      backup: yes
    with_items:
      - "###### Providing sudo access for service id docmgr"
      - "docmgr ALL=(ALL) NOPASSWD: ALL"

