---
- name: Playbook to upgrade / install Symantec Endpoint Protection to 14.3
  hosts: servers
  gather_facts: false
  become: yes
  become_method: sudo

  tasks:

    - name: Uninstall existing Symantec client
      shell: cd /opt/Symantec/symantec_antivirus && yes | ./uninstall.sh
      ignore_errors: True

    - name: Sleep for 10 seconds
      shell: sleep 10

    - name: Copy SEP client 14.3 package to servers under /var/tmp
      copy:
        src: /root/ansible/files/SymantecEndpointProtection14.3/SymantecEndpointProtection
        dest: /var/tmp/
        owner: root
        group: root
        mode: '0755'

    - name: Changing file permission to root
      file:
        path: "{{ item }}"
        owner: root
        group: root 
        mode: '0775'
      with_items:
      - /var/tmp/SymantecEndpointProtection/install.sh
      - /var/tmp/SymantecEndpointProtection/pkg.sig

    - name: Trigger Install Symantec Endpoint client at the background
      shell: PATH=/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin && cd /var/tmp/SymantecEndpointProtection && nohup ./install.sh -i </dev/null >/var/tmp/sepinstall.log 2>&1 &
      ignore_errors: True

