---
- name: remove the user
  hosts: servers
  remote_user: pandiasadmin
  become: yes
  become_method: sudo
  gather_facts: false

  tasks:
    - name: remove user cmfsme
      user:
        name: "{{ item.user }}"
        state: absent
        remove: yes
      with_items:
      - user: "taddmcfm"

    - name: Copy mef3 perl script with owner and permissions
      copy:
        src: /home/kpandian/ansible/files/iam_extract_ibm.pl
        dest: /tmp
        owner: root
        group: root
        mode: '0755'

    - name: Execute mef3 script
      shell: cd /tmp && ./iam_extract_ibm.pl --customer AMTRAK
      ignore_errors: True

    - name: Find the mef3 files under /tmp and register the output
      find:
        paths: /tmp
        patterns: '*.mef3'
        age: "-1h"
      register: findfiles

    - name: Fetch mef3 files from remote server
      fetch:
        src: "{{ item }}"
        dest: /home/kpandian/ansible/mef3output/
        flat: yes
      with_items:
        - "{{ findfiles.files | map(attribute='path') | list }}"

