---
- name: To copy VMTools from source to Remote servers
  hosts: indlist
  become: yes
  become_method: sudo
  gather_facts: false
  remote_user: kpandian
  tasks:
  - name: Copy vmtools package from laptop to remote server
    copy:
      src: "{{ item }}"
      dest: /tmp
      owner: root
      group: root
      mode: '0755'
    with_items:
      - "/home/kpandian/ansible/files/VMwareTools-10.3.10-12406962.tar.gz"

